services:
    # JSON-Importers
    sylius.importer.countries.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - null
            - "@sylius.manager.country"
            - "@sylius.processor.countries"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: country, format: json }

    sylius.importer.customer_group.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - null
            - "@sylius.manager.customer_group"
            - "@sylius.processor.customer_groups"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer_group, format: json }

    sylius.importer.payment_methods.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - null
            - "@sylius.manager.payment_method"
            - "@sylius.processor.payment_methods"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: payment_method, format: json }

    sylius.importer.tax_categories.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - null
            - "@sylius.manager.tax_category"
            - "@sylius.processor.tax_categories"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: tax_category, format: json }


    sylius.importer.customers.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - null
            - "@sylius.manager.customer"
            - "@sylius.processor.customers"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer, format: json }

    sylius.importer.taxons.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - null
            - "@sylius.manager.taxon"
            - "@sylius.processor.taxonomies"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: taxonomy, format: json }
